"""Comprehensive cleanup of stale reports, orphan data, and old experiments.

Removes:
1. Report JSON files for experiments that no longer exist
2. Stale graph_experiment_*.json files (engine-generated)
3. Old phase script outputs that reference deleted experiments
4. Orphan job results in the DB
5. Stale staging/archive entries
6. Old partial_loop_result.json
7. Clears all completed/failed/cancelled jobs from DB
"""
import json
import os
import sqlite3
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
REPORTS = REPO / "reports"
OUTPUTS = REPO / "outputs"
BACKEND_REPORTS = REPO / "backend" / "reports"
DB_PATH = REPO / "backend" / "data" / "glossa.db"

# Load current experiment IDs
exp_dir = REPO / "backend" / "glossa_lab" / "experiments" / "graphs"
current_exp_ids = set()
if exp_dir.exists():
    for f in exp_dir.glob("*.json"):
        if not f.name.startswith("_"):
            current_exp_ids.add(f.stem)

print(f"Current experiments: {len(current_exp_ids)}")
print(f"  {sorted(current_exp_ids)[:10]}...")

removed_files = 0
removed_bytes = 0

# ── 1. Clean stale report files ──────────────────────────────────────
print("\n=== 1. STALE REPORT FILES ===")

# graph_experiment_*.json files (auto-generated by engine)
for f in REPORTS.glob("graph_experiment_*.json"):
    size = f.stat().st_size
    f.unlink()
    removed_files += 1
    removed_bytes += size
    print(f"  Removed: {f.name} ({size//1024}KB)")

# Experiment result files that reference non-existent experiments
for f in REPORTS.glob("*.json"):
    stem = f.stem
    # Skip non-experiment files
    if stem in ("foundation_check_report", "anchor_quality_audit",
                "INDUS_FINAL_ANCHORS", "icit_extracted_corpus"):
        continue
    # Check if this is an experiment result
    if stem in current_exp_ids:
        continue  # Valid experiment, keep
    # Check if it's a phase report
    if stem.startswith("phase") and "_" in stem:
        continue  # Phase reports are historical, keep

    # Check file content to see if it references an experiment
    try:
        data = json.loads(f.read_text(encoding="utf-8"))
        exp_id = data.get("exp_id", "")
        if exp_id and exp_id not in current_exp_ids:
            size = f.stat().st_size
            f.unlink()
            removed_files += 1
            removed_bytes += size
            print(f"  Removed: {f.name} (orphan exp_id={exp_id}, {size//1024}KB)")
    except Exception:
        pass

# ── 2. Clean outputs directory ───────────────────────────────────────
print("\n=== 2. STALE OUTPUTS ===")

# partial_loop_result.json — stale after loop completion
partial = OUTPUTS / "partial_loop_result.json"
if partial.exists():
    size = partial.stat().st_size
    partial.unlink()
    removed_files += 1
    removed_bytes += size
    print(f"  Removed: partial_loop_result.json ({size//1024}KB)")

# phase_state.json — clear completed phase data
phase_state = OUTPUTS / "phase_state.json"
if phase_state.exists():
    try:
        state = json.loads(phase_state.read_text(encoding="utf-8"))
        # Keep only the override_phase key, clear completed actions
        clean = {}
        if "override_phase" in state:
            clean["override_phase"] = state["override_phase"]
        phase_state.write_text(json.dumps(clean, indent=2), encoding="utf-8")
        print(f"  Cleaned phase_state.json (cleared {len(state)} old entries)")
    except Exception:
        pass

# Old analysis directories
for d in OUTPUTS.glob("analysis/*"):
    if d.is_file() and d.suffix == ".json":
        try:
            data = json.loads(d.read_text(encoding="utf-8"))
            # Check if it references current data
            if not data:
                size = d.stat().st_size
                d.unlink()
                removed_files += 1
                removed_bytes += size
        except Exception:
            pass

# ── 3. Clean anchor staging ──────────────────────────────────────────
print("\n=== 3. ANCHOR STAGING ===")

staging = OUTPUTS / "anchor_staging.json"
if staging.exists():
    try:
        items = json.loads(staging.read_text(encoding="utf-8"))
        if isinstance(items, list):
            before = len(items)
            # Remove expired/archived entries
            clean = [i for i in items if i.get("review_status") in ("staged", "approved")]
            if len(clean) < before:
                staging.write_text(json.dumps(clean, indent=2, ensure_ascii=False), encoding="utf-8")
                print(f"  Cleaned staging: {before} → {len(clean)} (removed {before-len(clean)} stale)")
            else:
                print(f"  Staging clean: {len(clean)} entries")
    except Exception:
        pass

archive = OUTPUTS / "anchor_staging_archive.json"
if archive.exists():
    size = archive.stat().st_size
    print(f"  Archive: {size//1024}KB (keeping for audit trail)")

# ── 4. Clean DB: jobs and results ────────────────────────────────────
print("\n=== 4. DATABASE CLEANUP ===")

if DB_PATH.exists():
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row

    # Count jobs by status
    rows = conn.execute("SELECT status, COUNT(*) as cnt FROM jobs GROUP BY status").fetchall()
    for r in rows:
        print(f"  Jobs {r['status']}: {r['cnt']}")

    # Delete all finished jobs
    result = conn.execute(
        "DELETE FROM job_results WHERE job_id IN "
        "(SELECT id FROM jobs WHERE status IN ('completed','failed','cancelled'))"
    )
    deleted_results = result.rowcount

    result = conn.execute(
        "DELETE FROM jobs WHERE status IN ('completed','failed','cancelled')"
    )
    deleted_jobs = result.rowcount

    # Also clean orphan results (results without a parent job)
    result = conn.execute(
        "DELETE FROM job_results WHERE job_id NOT IN (SELECT id FROM jobs)"
    )
    orphan_results = result.rowcount

    conn.commit()
    print(f"  Deleted {deleted_jobs} finished jobs, {deleted_results} results, {orphan_results} orphan results")

    # Verify clean state
    remaining = conn.execute("SELECT COUNT(*) as cnt FROM jobs").fetchone()["cnt"]
    print(f"  Remaining jobs: {remaining}")

    conn.close()

# ── 5. Clean backend reports (engine-generated) ─────────────────────
print("\n=== 5. BACKEND REPORTS ===")

# The backup file from anchor cleanup
backup = BACKEND_REPORTS / "INDUS_FINAL_ANCHORS.json.bak"
if backup.exists():
    size = backup.stat().st_size
    print(f"  Anchor backup: {size//1024}KB (keeping for safety)")

# ── 6. Clear localStorage caches note ────────────────────────────────
print("\n=== 6. FRONTEND CACHES ===")
print("  Note: Clear these in browser DevTools console:")
print("    localStorage.removeItem('geb_run_cache')")
print("    localStorage.removeItem('glossa_seq_run_queue')")
print("    localStorage.removeItem('glossa_dashboard_insight_v2')")
print("    localStorage.removeItem('glossa_promote_result')")
print("    localStorage.removeItem('glossa_chat_history')")
print("    location.reload()")

# ── Summary ──────────────────────────────────────────────────────────
print(f"\n{'='*60}")
print(f"CLEANUP SUMMARY")
print(f"{'='*60}")
print(f"Files removed: {removed_files}")
print(f"Space freed: {removed_bytes/1024:.0f} KB")
print(f"Jobs cleaned: {deleted_jobs}")
print(f"Results cleaned: {deleted_results + orphan_results}")
print(f"\n✅ Clean slate ready")
