"""Spec 026 Stage S2 — impact register builder.

Reads the extraction inventory (``specs/026-rcph-framework-transfer/
working/inventory.json``) and the authored classification table
(``register-classifications.json``) and emits the impact register in
JSON, CSV, and Markdown under the spec directory.

The builder is deliberately strict (Spec 026 FR-026-5): every
inventory item must appear exactly once in the classification
table, every classification must be one of the five frozen
classes, and every RERUN-REQUIRED row must name its rerun. Any
violation aborts the build — a silently incomplete register is
the failure mode this spec exists to prevent.

Usage: python backend/scripts/spec026_register_build.py [--check]
``--check`` rebuilds in memory and diffs against the committed
register files (used by tests / CI).
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SPEC_DIR = REPO_ROOT / "specs" / "026-rcph-framework-transfer"
INVENTORY = SPEC_DIR / "working" / "inventory.json"
CLASSIFICATIONS = SPEC_DIR / "register-classifications.json"

CLASSES = {
    "RERUN-REQUIRED",
    "REPRODUCE-ONLY",
    "REINTERPRET-ONLY",
    "UNAFFECTED",
    "NOT-RERUNNABLE",
}

REGISTER_FIELDS = [
    "item_id",
    "kind",
    "title",
    "claims",
    "historical_label",
    "data_sources",
    "origin_groups",
    "controls",
    "control_failures",
    "frozen",
    "uncertainty_reported",
    "grid_complete",
    "independence_notes",
    "classification",
    "rationale",
    "rerun_spec",
]


def build_rows() -> list[dict]:
    inventory = json.loads(INVENTORY.read_text("utf-8"))
    classifications = json.loads(CLASSIFICATIONS.read_text("utf-8"))

    inv_ids = [item["item_id"] for item in inventory]
    if len(inv_ids) != len(set(inv_ids)):
        raise SystemExit("inventory contains duplicate item_ids")
    missing = [i for i in inv_ids if i not in classifications]
    extra = [i for i in classifications if i not in set(inv_ids)]
    if missing or extra:
        raise SystemExit(
            f"classification table mismatch: missing={missing} extra={extra}"
        )

    rows: list[dict] = []
    for item in inventory:
        cls = classifications[item["item_id"]]
        klass = cls["classification"]
        if klass not in CLASSES:
            raise SystemExit(f"{item['item_id']}: unknown class {klass!r}")
        if klass == "RERUN-REQUIRED" and not cls.get("rerun_spec"):
            raise SystemExit(f"{item['item_id']}: RERUN-REQUIRED without rerun_spec")
        row = {field: item.get(field) for field in REGISTER_FIELDS[:13]}
        row["classification"] = klass
        row["rationale"] = cls["rationale"]
        row["rerun_spec"] = cls.get("rerun_spec")
        rows.append(row)
    return rows


def render_json(rows: list[dict]) -> str:
    return json.dumps({"register": rows}, indent=1, ensure_ascii=False) + "\n"


def render_csv(rows: list[dict]) -> str:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=REGISTER_FIELDS, lineterminator="\n")
    writer.writeheader()
    for row in rows:
        writer.writerow(
            {
                f: (json.dumps(row[f], ensure_ascii=False) if not isinstance(row[f], (str, type(None))) else (row[f] or ""))
                for f in REGISTER_FIELDS
            }
        )
    return buf.getvalue()


def render_md(rows: list[dict]) -> str:
    counts: dict[str, int] = {}
    for row in rows:
        counts[row["classification"]] = counts.get(row["classification"], 0) + 1
    lines = [
        "# Spec 026 — Impact Register",
        "",
        "Generated by `backend/scripts/spec026_register_build.py` from",
        "`working/inventory.json` + `register-classifications.json` under the",
        "criteria frozen at Stage S1 (`classification-criteria.md`).",
        "Reclassification requires a dated amendment to the criteria file.",
        "",
        "## Counts by class",
        "",
        "| Class | Rows |",
        "|---|---|",
    ]
    for klass in sorted(counts):
        lines.append(f"| {klass} | {counts[klass]} |")
    lines += ["", f"Total rows: {len(rows)}", "", "## Rows", ""]
    for row in rows:
        lines.append(f"### {row['item_id']} — {row['classification']}")
        lines.append("")
        lines.append(f"- Title: {row['title']}")
        lines.append(f"- Historical label: {row['historical_label']}")
        lines.append(f"- Rationale: {row['rationale']}")
        if row["rerun_spec"]:
            lines.append(f"- Rerun: {row['rerun_spec']}")
        lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    rows = build_rows()
    outputs = {
        SPEC_DIR / "impact-register.json": render_json(rows),
        SPEC_DIR / "impact-register.csv": render_csv(rows),
        SPEC_DIR / "impact-register.md": render_md(rows),
    }
    if args.check:
        drift = [
            str(p) for p, content in outputs.items()
            if not p.exists() or p.read_text("utf-8") != content
        ]
        if drift:
            print(f"register drift: {drift}", file=sys.stderr)
            return 1
        print(f"register check OK: {len(rows)} rows")
        return 0
    for path, content in outputs.items():
        path.write_text(content, "utf-8")
    print(f"register written: {len(rows)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
